# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = './../my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'NativeWithFlutter2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeWithFlutter2
install_all_flutter_pods(flutter_application_path)

   
  target 'NativeWithFlutter2Tests' do
#    inherit! :search_paths
    # Pods for testing
#    install_all_flutter_pods(flutter_application_path)
  end

  target 'NativeWithFlutter2UITests' do
#    inherit! :search_paths
    # Pods for testing
#    install_all_flutter_pods(flutter_application_path)
  end

end
